### ISSUE TITLE
Python, gumbo and Ubuntu 14.04

### ISSUE THREAD

**Issue by rob70** [Sigil-Ebook/sigil-gumbo#1]
I ran across an issue which is mentioned in the repository google/gumbo-parser. The issue is there entitled "Python interface seems to not work" ( google/gumbo-parser/issues/356 ). I am using Ubuntu 14.04.

The ```sudo python setup.py install``` script seems not to install the libgumbo.so.1.0.0-file in the gumbo package.

I found Nick Alam's solution to be helpful. He symlinks the libgumbo file to the gumbo python package:

```ln -s /usr/local/lib/libgumbo.so.1.0.0 /usr/local/lib/python2.7/dist-packages/gumbo-0.10.1-py2.7.egg/gumbo/libgumbo.so```

In my case the symlink read:

```sudo ln -s /usr/local/lib/libgumbo.so.1.0.0 /usr/local/lib/python3.4/dist-packages/gumbo-1.0.0-py3.4.egg/gumbo/libgumbo.so```

**Comment by kevinhendricks** [comment]
Thank you for the head's up.  We in the Sigil project use our own version of the gumbo library and our own version of the python interface to it installed as part of Sigil.

**Comment by rob70** [comment]
Yes, I noticed that Sigil was working because the test plugin script ran successfully independent of this. However, the python interpreter could not import gumbo without this addition. Thank you.

**Comment by kevinhendricks** [comment]
That is because this project is a placeholder for code that actually exists inside the Sigil tree and Sigil uses a renamed library to prevent clashes with the main gumbo library and a renamed and modified python interface which knows how to find the renamed library inside Sigil.

You should not use or need this project as the proper and working gumbo code is stored and built in the main Sigil tree.

See the code here:

https://github.com/Sigil-Ebook/Sigil/tree/master/src/Resource_Files/plugin_launchers/python

and here:

https://github.com/Sigil-Ebook/Sigil/tree/master/internal/gumbo

If you are trying to use Sigil's version of gumbo in a Sigil plugin, please see the testme3 plugin for examples from the Sigil Plugin Development thread in the Sigil Forum on www.mobileread.com

**Comment by kevinhendricks** [comment]
In case this may be useful to you or others, here a snippet from plugin.py that shows how to access Sigil's version of gumbo in a Sigil Plugin:

```
    # examples for using the bs4/gumbo parser to process xhtml
    print("\nExercising: the gumbo bs4 adapter")
    import sigil_gumbo_bs4_adapter as gumbo_bs4
    samp = """
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-US">
<head><title>testing & entities</title></head>
<body>
  <p class="first second">this&nbsp;is&#160;the&#xa0;<i><b>copyright</i></b> symbol "&copy;"</p>
  <p xmlns:xlink="http://www.w3.org/xlink" class="second" xlink:href="http://www.ggogle.com">this used to test atribute namespaces</p>
</body>
</html>
"""
    soup = gumbo_bs4.parse(samp)
    for node in soup.find_all(attrs={'class':'second'}):
        print(node)
```
